name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      name: Build
      runs-on: ubuntu-latest
      steps:
	-name: - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.139.162.50.10 }}
        username: ${{ secrets.root }}
        password: ${{ secrets.root }}
        port: ${{ secrets.22 }}
        script: whoami
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn clean install
